Repository pagopa/pagopa-fdr-re-to-datastore, pull requests merged in 2023-09, with the labels that each got.

#6 fix re mapping
  pom.xml
  src/main/java/it/gov/pagopa/fdrretodatastore/FdrReEventToDataStore.java
Labels: bug

#7 [NOD-476] feat: migrating deploy from AZDO to GHA
  .github/workflows/00_anchore.yml
  .github/workflows/01_assignee.yml
  .github/workflows/02_check_pr.yml
  .github/workflows/03_code_review.yml
  .github/workflows/04_release_deploy.yml
  .github/workflows/04_self_hosted.yml
  .github/workflows/check_metadata_pr.yml
  .github/workflows/deploy.yml
  .github/workflows/sonar_analysis.yml
  .gitignore
  .identity/.terraform.lock.hcl
  .identity/00_data.tf
  .identity/02_application_action.tf
  .identity/03_github_environment.tf
  .identity/99_main.tf
  .identity/99_variables.tf
  .identity/env/dev/backend.ini
  .identity/env/dev/backend.tfvars
  .identity/env/dev/terraform.tfvars
  .identity/env/prod/backend.ini
  .identity/env/prod/backend.tfvars
  .identity/env/prod/terraform.tfvars
  .identity/env/uat/backend.ini
  .identity/env/uat/backend.tfvars
  .identity/env/uat/terraform.tfvars
  .identity/terraform.sh
Labels: ignore-for-release, size/large

#8 chore: removed AZDO pipeline
  .devops/deploy-pipelines.yml
Labels: ignore-for-release
